# Generated by Django 4.2.7 on 2023-11-23 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('sitio_web', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateField()),
                ('genero', models.CharField(choices=[('N', 'Novela'), ('E', 'Ensayo'), ('C', 'Cuento'), ('P', 'Poesía'), ('T', 'Teatro'), ('O', 'Otros')], max_length=1)),
                ('isbn', models.PositiveIntegerField(max_length=13)),
                ('resumen', models.TextField()),
                ('disponibilidad', models.CharField(choices=[('D', 'Disponible'), ('P', 'Prestado'), ('E', 'En proceso de préstamo')], max_length=1)),
                ('autores', models.ManyToManyField(to='biblioteca.autor')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.editorial')),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.PositiveIntegerField(max_length=9),
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField()),
                ('fecha_devolucion', models.DateField()),
                ('estado', models.CharField(choices=[('P', 'Prestado'), ('D', 'Devuelto')], max_length=1)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
