# Generated by Django 4.2.7 on 2023-11-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_alter_autor_nombre_alter_editorial_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='disponibilidad',
            field=models.CharField(choices=[('D', 'Disponible'), ('P', 'Prestado')], max_length=1),
        ),
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.CharField(choices=[('N', 'Novela'), ('C', 'Cuento'), ('P', 'Poesía'), ('T', 'Teatro'), ('O', 'Otros')], max_length=1),
        ),
    ]
